name: second

services:
  db:
    image: mysql:8.2.0
    volumes:
      - db_data:/va/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD: